### PR TITLE
feat: adopt fluid-lint-all (resolves #66)

### LINKED ISSUE #66: Adopt fluid-lint-all
Once the new [fluid-lint-all](https://github.com/fluid-project/fluid-lint-all) package is ready, this project should adopt it and replace `fluid-grunt-lint-all`.

### PR DESCRIPTION
**Pull request by greatislander**
Adopts dev version of `fluid-lint-all` for project linting.

### CODE REVIEW

**Review by BlueSlug — COMMENTED** [review]
The changes all look good, though the process seems to crash when it runs into linting errors, rather than finish successfully and indicate the errors.

I ran the `lint` script after running the `start` script, and it complained about the mixed line endings in `src\_data\assets.json` (this file should probably be excluded from linting). I was able to achieve the same crash-out by introducing intentional linting issues.

I've saved the log to a gist, in case it's helpful: https://gist.github.com/BlueSlug/666d4fdb55f172684a93235ff1553e07

**Comment by greatislander** [comment]
> The changes all look good, though the process seems to crash when it runs into linting errors, rather than finish successfully and indicate the errors.
> 
> I ran the `lint` script after running the `start` script, and it complained about the mixed line endings in `src\_data\assets.json` (this file should probably be excluded from linting). I was able to achieve the same crash-out by introducing intentional linting issues.
> 
> I've saved the log to a gist, in case it's helpful: https://gist.github.com/BlueSlug/666d4fdb55f172684a93235ff1553e07

Thanks, @BlueSlug — left a comment upstream for @the-t-in-rtf. I agree that that file should be excluded from linting so I've added it to the linting configuration as a manual exclusion for now. Can you re-test?

**Comment by BlueSlug** [comment]
> > The changes all look good, though the process seems to crash when it runs into linting errors, rather than finish successfully and indicate the errors.
> > I ran the `lint` script after running the `start` script, and it complained about the mixed line endings in `src\_data\assets.json` (this file should probably be excluded from linting). I was able to achieve the same crash-out by introducing intentional linting issues.
> > I've saved the log to a gist, in case it's helpful: https://gist.github.com/BlueSlug/666d4fdb55f172684a93235ff1553e07
> 
> Thanks, @BlueSlug — left a comment upstream for @the-t-in-rtf. I agree that that file should be excluded from linting so I've added it to the linting configuration as a manual exclusion for now. Can you re-test?

Looks like it's still checking that file, despite the exclude :(

Unrelated, is `Gruntfile.js` still required?

**Comment by greatislander** [comment]
@BlueSlug Good catch re: Gruntfile. It also escaped my attention that the failing check was `eslint.json`, not `jsonlint` — can you test again with the most recent commit?

**Comment by BlueSlug** [comment]
The linter is no longer complaining about `assets.json` 👍🏻

**Comment by the-t-in-rtf** [comment]
I commented on the gist, but just to close the loop here, the linting doesn't crash per se, it just exits with a non-zero code if there are errors, so that you can use it block CI or multi-stage npm scripts that use `&&`.  I'm glad you figured out the task name, I updated the docs to make that clearer.

See above comments about writing up the `.gitignore` improvement as a new issue.

**Pull request merged**
